/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libsdl_app_CallNativeMethods */

#ifndef _Included_org_libsdl_app_CallNativeMethods
#define _Included_org_libsdl_app_CallNativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_libsdl_app_CallNativeMethods
 * Method:    changeHanioLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_libsdl_app_CallNativeMethods_changeHanioLevel
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_libsdl_app_CallNativeMethods
 * Method:    changeFPS
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_libsdl_app_CallNativeMethods_changeFPS
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_libsdl_app_CallNativeMethods
 * Method:    startMove
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libsdl_app_CallNativeMethods_startMove
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
